### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by MarvAmBass** [lieuwex/whapp-irc#27]
Hi there,

thanks for your work. unfortunately it seems to have an issue with my archived chats.
after starting the container I see the following:

```
f7d3XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2018/09/26 07:47:56 error: could not perform (childNodeCountUpdated) operation on node 8 (wait node): timeout waiting for node `8`
2018/09/26 07:48:11 (2018-09-26 07:48:11) status->XXX: logged in
2018/09/26 07:48:11 4911xxx
[all my archived chats]
2018/09/26 07:48:14 4915xxx
panic: runtime error: index out of range
                                                                                                                                                                                      
goroutine 9 [running]:            
main.(*Chat).Identifier(0xc4201add40, 0xc422e5d9c0, 0x4)
        /go/src/whapp-irc/types.go:52 +0xe5
main.(*Connection).addChat(0xc42015c600, 0xc422e5d9c0, 0x4, 0xc422e5d9c4, 0xc, 0x0, 0x1, 0xc422e5d9f8, 0x4, 0xc422e5da00, ...)
        /go/src/whapp-irc/connection.go:381 +0x3ec                                                                                                                   
main.(*Connection).setup(0xc42015c600, 0x0, 0x0)                
        /go/src/whapp-irc/connection.go:478 +0x44e                                                                                
main.(*Connection).BindSocket.func2.1(0x8a2520, 0x5)               
        /go/src/whapp-irc/connection.go:115 +0x48
whapp-irc/vendor/github.com/avast/retry-go.Do(0xc4200b9e70, 0xc4201a6e50, 0x2, 0x2, 0x0, 0xc4201b2000)
        /go/src/whapp-irc/vendor/github.com/avast/retry-go/retry.go:87 +0x16e
main.(*Connection).BindSocket.func2(0xc42003cf20, 0x1, 0xc42003cf08)
        /go/src/whapp-irc/connection.go:113 +0x287                 
main.(*Connection).BindSocket.func3(0xc42001ee20, 0x9a22c0, 0xc420020400, 0xc4200821e0, 0xc42015c600, 0xc42001ee30)
        /go/src/whapp-irc/connection.go:144 +0x1a5
created by main.(*Connection).BindSocket
        /go/src/whapp-irc/connection.go:129 +0x213    
```

maybe you have an Idea what could cause this problem

Thanks :)

**Comment by MarvAmBass** [comment]
okay I looked into this issue and I was able to solve it

the problem is, that sometimes the username is empty (I'm pretty sure that the user which makes all this brake blocked me here)

I fixed this by checking if the username is empty and replacing it with a static string (don't know if this has any side effects)

`types.go` line 53
```
	if len(name) == 0 {
		name = "UnkownWAUser"
	}
```

**Comment by lieuwex** [comment]
This indeed is because of an empty user name.
But since I've never experienced it myself, I'm curious.
Are you sure the user is just a user that blocked you (since I would expect whapp-irc to just take their phone number in that case), or can it be an user which only contains an invalid symbol (such as an emoji) as their name? (We fully remove invalid symbols, but try to convert stuff like ä to a.)

If it really happens because of an user that blocked you, I guess another option would be to just skip the contact. Since I feel like it wouldn't be really useful to send a message to a contact that blocked you, but maybe that actually has consequences like retrieving the last messages before a user blocked you, I don't know.

**Comment by lieuwex** [comment]
As a side note now I'm actually unsure what happens with a group chat that only contains an emoji in its name.

**Comment by lieuwex** [comment]
I guess I prefer to just skip the user then, and maybe log some information in on `stderr`.

When multiple contacts have an empty name, they all get `UnkownWAUser` as name which basically collapses all the users into one. Which will lead to incontinuities when receiving and mostly sending messages from/to them.

But I still find this a peculiar problem.

**Comment by MarvAmBass** [comment]
Skipping would be fine!

Yeah I also thought about generating some unique id/suffix for users with this issue - to avoid merging those into one `UnkownWAUser `.

maybe I can investigate this user a bit further - looking into the dom using chrome developer tools etc.

**Comment by lieuwex** [comment]
Sure thing! I will push a fix where I skip the users soon then.
Investigating might be useful, you can post updates here if you find something interesting.

**Comment by lieuwex** [comment]
Hmmm is it possible that numbers don't start with a + in your WhatsApp?
Here in NL they start with +31.... and I match for a + at the string start

**Comment by lieuwex** [comment]
The fix has been pushed and the container should be done building in a little while.

**Comment by MarvAmBass** [comment]
perfect thanks - it works now!

I was also investigating the problem. The person has a whatsapp username which consists of two emojis. So in your string to safe_string method this seems to be translated into `""`.

I don't know why it is not able to fetch the Phone number as fallback - it looks normal `+49 174<cencored>5` - like every other number of people I don't have in my address book.

One possible nice solution might be to translate the emojis to thier names. for example 🍫  to `chocolate_bar`. Maybe there is already a library which does that.
https://github.com/kyokomi/emoji/blob/master/emoji_codemap.go might help here. this way we might also be able to implement emoji support for irc.
