### ISSUE TITLE
Connecting but never online on Miranda NG

### ISSUE THREAD

**Issue by XP-Fan** [lieuwex/whapp-irc#28]
So after fighting a lot I finaly managed to connect my IRC-Client, I received the QR-Code and I logged in. However, always when I try to send a message it says protocol is offline. When I look into my instant messengers tray icon, I can see that the IRC-Account is on "connecting..." but it does never completely ge the online state. Why?

**Comment by XP-Fan** [comment]
Well, I can login, after I do, I get a link to scan the code from. Also if I log off and on again with my irc-client it works fine. My problem is that the client does not understand the fact that it is allready online, so I do receive messages, but if I wanna send something I get an error message stating "protocol is offline." So either my IRC-Client (Miranda NG), or Whappirc's builtin iRC-Server must present the online-state in a wrong way. The funny thing is, however, yesterday at night I managed to get it all working over lima-city's IRC-XMPP-Transport. However it doesn't want to login any longer now. For Miranda it's still the same: I can login, If I do so I receive all my WhatsApp-Messages in the IRC-Client, but the clients status keeps reading "connecting…" instead of "online", thus I can receive and read everything, but not reply. Anyway: I have no clue if this issue is related to whappirc or Miranda NG.

**Comment by lieuwex** [comment]
Sorry for my abrupt and very long absence, I had some personal stuff I had to deal with which pretty much stopped me from working on my side projects.

I'm happy to see you made a lot of progress anyways.

Could you enable verbose logging by setting the environment variable `LOG_LEVEL` to `verbose`? (should probably add that to the README as well).
And after that restarting the container, logging in and getting the logs the way @MarvAmBass described?
The logs can contain pretty personal stuff, so I would advise you to take a look before posting here (or you can sent it directly to my personal mail if you trust me).

It's also a big possibility that I didn't implement the IRC protocol correctly, to be frank, the project started as one big hack.

**Comment by lieuwex** [comment]
Looking at https://modern.ircdocs.horse/#connection-registration, I feel like whapp-irc is correct. But I'm not 100% sure.

**Comment by XP-Fan** [comment]
Sorry but can you tell me how I am supposed to shutdown whapp-irc? Just doing "poweroff" on the Debian-VM is not the right way I guess. Anyway how do I give it the chance to safe data? I never find things in /root if I look at it with cd and ls.

**Comment by XP-Fan** [comment]
Seems like now everything is broken. It connects, it welcomes me in the server window, but I do not get an QR-Code any longer. Did you make any changes since yesterday?

**Comment by XP-Fan** [comment]
Hey can you please help me, whapp-Irc was used to work for me with the following lines:


docker run -d \
            --name whapp-irc \
            -v PATH_TO_DIR_FOR_DATA_HERE:/root \
            -p 6667:6060 \
            -p 3000:3000 \
            -e "HOST=server.neverseen.de" \
            lieuwex/whapp-irc





As of your latest commits it doesn't give me an QR-Code any linger. As I do not understand anything about the configuration stuff I type here, I guess it is because I didn't specify an log-level or an map-provider. But what must I do now to get it back working?

**Comment by XP-Fan** [comment]
Anyway, the fact that Miranda NG is connecting but never showing the IRC-Chat as online is a problem from mirandas side, as miranda does not support IRCV3, so you did do it correctly I guess.

**Comment by MarvAmBass** [comment]
Hi there,

`PATH_TO_DIR_FOR_DATA_HERE` really is a bit confusing - but here you just specify the path where all the data is saved (login information etc.).

Look at this example. When ran under linux or macos it will use the _hidden_ directory `.whatsapp` inside the users home folder to store the data.

```
docker run -d \
	--name whapp-irc \
	-v $HOME/.whatsapp:/root \
	-p 6667:6060 \
	-p 3000:3000 \
	-e "HOST=localhost" \
	lieuwex/whapp-irc
```

If you use docker for windows/are new to docker in general - you should read about how to use docker for windows first - after that everything will be much clearer.

**Comment by XP-Fan** [comment]
Well, I am on Windows XP and running Docker from within an Debian VM. To be fair, I am not only new to docker, but also to linux. If I get you right, there is no need for me to specify log-level or map-provider? anyway: How do I create a log at all? Latest version does still not work for me: "status" doesn't send me the QR-Code. Do you know how to fix this, or how to revert to a previous version?

**Comment by MarvAmBass** [comment]
ohh okay, I didn't need to specify log-level or anything. but it depends on what you want to do - I just noticed that you have some general problems here and came to help.

It only sends the qr-code when it needs it. if it worked one time, it should no longer ask for this.
maybe you can delete the folder which you put into `PATH_TO_DIR_FOR_DATA_HERE` and start from scratch

I noticed that everything starts running when I connect to the server using my irc client.

you can use `docker logs -f whapp-irc` to see and follow the logs.

maybe you can try this:

```
rm -rf "$HOME/.whatsapp"
docker rm -f whapp-irc
docker run -d \
	--name whapp-irc \
	-v "$HOME/.whatsapp:/root" \
	-p 6667:6060 \
	-p 3000:3000 \
	-e "HOST=DEBIAN_VM_IP/HOSTNAME" \
	lieuwex/whapp-irc
docker logs -f whapp-irc
```

**Comment by XP-Fan** [comment]
Well, what I also do not really understand is: There are now some backslashes missing. Am I supposed to send these commands one after another, or can I just take all your code and paste it into putty as is?

**Comment by MarvAmBass** [comment]
just copy+paste as it is.
it will run 4 commands, with one multiline command

**Comment by XP-Fan** [comment]
All right, so this is what I get:


root@debianvm:~# docker logs -f whapp-irc

2018/10/05 12:38:18 err while setting up: timeout waiting for initial target

2018/10/05 12:38:21 err while setting up: timeout waiting for initial target

**Comment by XP-Fan** [comment]
Now I got a message from "status":



   giving up trying to setup whapp bridge: All attempts fail:

**Comment by lieuwex** [comment]
To stop you can use `docker stop whapp-irc`, but actually it should be unnecessary, since whapp-irc stores everything on disk as soon as it's retrieved (and it's not a problem if something hasn't been saved, really).

To just let whapp-irc resume it should be enough to run:
```
docker run -d \
	--name whapp-irc \
	-v "$HOME/.whatsapp:/root" \
	-p 6667:6060 \
	-p 3000:3000 \
	-e "HOST=server.neverseen.de" \
	-e "LOG_LEVEL=verbose"
	lieuwex/whapp-irc
```

For sending logs I recommend using https://bin.disroot.org/ (hoping it works good enough with a screenreader, with some quick testing it seems to be useable) and sending the generated link to my [personal mail address](mailto:lieuwerooijakkers@gmail.com).
The upload site encrypts the logs so that nobody at disroot.org can peek into the logs.

**Comment by XP-Fan** [comment]
Well, I can not overtake

        -e "LOG_LEVEL=verbose"

without it complaining that docker run would at least require 1 argument. I think I gave it lots of arguments? However, if I keep this away, I get an conflict that the name whapp-irc would allready be in use. Anyway: It looks like whapp-irc doesn't like itself having an dynamic IP, or maybe the lima XMPP-IRC-Transport doesn't like that, which basically sucks, as messages are not gonna be transferred if my computer is shut down, and I need someone to scan the QR-Code every day. Can you please help me, what do I do wrong?

**Comment by lieuwex** [comment]
Okay my bad.

Now you should be able to do:
```
docker rm -f whapp-irc
docker run -d \
	--name whapp-irc \
	-v "$HOME/.whatsapp:/root" \
	-p 6667:6060 \
	-p 3000:3000 \
	-e "HOST=server.neverseen.de" \
	-e "LOG_LEVEL=verbose" \
        --restart=always \
	lieuwex/whapp-irc
```

(the old container has to be deleted, and I missed an backslash in the command in my previous message, therefore you got the error from Docker).

Then when it's running you can stop it using `docker stop whapp-irc`, as I stated (or just shutdown your server).

I also added the `restart=always` flag, which if I'm correct, should automatically restart the container after shutdown or a crash (I personally use docker-compose, so that's why I'm not very experienced with the normal Docker commands. However, setting that up is a bit too much for one container).

If, for some reason, the container has to be started manually again. It should be enough to run `docker start whapp-irc`.

That problem with dynamic IP sounds really weird, whapp-irc doesn't really care where it gets its connections from (it listens on every IP basically).
Maybe it can help to restart the container (or even server) after an IP change?
What kind of problems are you seeing with your dynamic IP?

If everything has been correctly set up (with the folders), scanning the QR code everyday shouldn't be necessary. I've seen some problems where it still prompts it, but 5 seconds after it will say 'logged in'.

**Comment by XP-Fan** [comment]
Okay, thanks, I'll try this. Well to be frank the longer I think about it, the more I come to the conclusion that the problem of the dynamic IP must be from the lima-transport side. If The servers IP changes, and whapp-irc wants to deliver a message to the transport, the transport refuses it, as it is coming from another IP. I must somehow wait for the miranda team to include IRC3 in order to be able to avoid this transport thing. Furthermore, I'm now gonna run an XMPP-Client on my server, cause I can imagine that the transport would refuse messages as long as I am not connected on XMPP. Anyway, what I also do not understand is: how am I supposed to define this whapp-irc/replay capability? I mean: If I shut down my computer at the evening, and restart it in the morning, it is not showing the messages that have arrived on my phone while my PC was off, which basically sucks. However, I do not have an whapp-irc/replay-option in my IRC-Client, neither in the XMPP-transport configuration, nor in miranda, as Miranda team didn't even know about whapp-ircs existence before I told them. And what do you mean by messages that the bridge missed? Does that mean I have to shutdown the computer and my server?

**Comment by lieuwex** [comment]
I will try to take a look at Miranda ASAP, to see if I can find a work-around on my side.

The `whapp-irc/replay` capability is sadly only available on IRCv3 clients, since it requires the `server-time` capability which is an IRCv3 extension. It _MIGHT_ be possible to hack around this by hardcoding the replay capability to on in the source code of whapp-irc. But I'm afraid it would lead to IRC clients becoming really confused and breaking apart.

As for "missed messages", I mean messages that were sent to you during the time your server was off or when you were logged out; basically all messages not yet sent to your IRC client.

**Comment by lieuwex** [comment]
As a side note: aren't there any IRCv3 capable IRC clients for Windows with good screen-reader support?

**Comment by XP-Fan** [comment]
Well, honestly I don't know, mainly because I also use Miranda for Facebook, Skype and XMPP itself. So it is quite comfortable to have them all in one. Anyway: I wouldn't know where to start, as I do also need to keep in mind that I'm running on Pentium 4 with 256 MBs of RAM. If minimized, Miranda can reduce itself to taking 624 KBs of RAM if needed, which I consider to be really efficient. However, if you have any recommendations, let me know. But please make sure that it is free of adware or junkware. I've also contacted the Miranda-Team, and Mr. Hazan is willing to implement IRC V3. However, I have no idea when he's gonna do it, as for example in 2017 an miranda version was released, the next one did take until may 2018, the version after that arrived like 2 weeks later, so, as for every open-source thing, you just never know when they're gonna finish what.

**Comment by XP-Fan** [comment]
Oh, well, and of course it must run on Windows XP.

**Comment by lieuwex** [comment]
With a quick look [AdiIRC](adiirc.com) or [mIRC](https://www.mirc.com/). The first one seems to have better screen reader support out-of-the-box, the latter requiring some configuration. Both have excellent [IRCv3 support](https://ircv3.net/software/clients.html#desktop-clients). It is of course a temporary solution until Miranda has IRCv3 support, and it kinda sucks to be honest. I hope Miranda adds IRCv3 support soon.

I'm afraid neither of the above clients can top the memory usage of Miranda, that's really impressive!

**Comment by lieuwex** [comment]
@XP-Fan Is it by the way possible if you could send the logs you sent to the miranda-ng owner to my [personal mail](mailto:lieuwerooijakkers@gmail.com). I'm pretty curious to see where stuff goes wrong,  I can't really test miranda-ng right now and reading through the whapp-irc code I couldn't really figure out a point of failure.

**Comment by XP-Fan** [comment]
Well, I send it, I hope it has any use for you as I had the feeling that it didn't serve anything for Mr. Hazan.

**Comment by lieuwex** [comment]
Okay, I pushed an update where I implemented the registration sequence stricter.
Could you try it out?
You can remove the old container and run a new one using:
```
docker rm -f whapp-irc
docker pull lieuwex/whapp-irc
docker run -d \
	--name whapp-irc \
	-v "$HOME/.whatsapp:/root" \
	-p 6667:6060 \
	-p 3000:3000 \
	-e "HOST=server.neverseen.de" \
	-e "LOG_LEVEL=verbose" \
	--restart=always \
	lieuwex/whapp-irc
```

**Comment by XP-Fan** [comment]
Well, just a sec, I'mm gonna fetch my phone and call my mother as I'll probably have to rescan the QR-Code then. Right?

**Comment by XP-Fan** [comment]
Well, actually now indeed miranda is showing as online. However, I can now neither read nor write messages, but don't worry, I am pritty sure that this is my fault, as I connected this IRC-XMPP-Transport before, and this just never logs off properly. So what I am gonna do is just reset the VM to a state where it didn't ever have contact to whapp-irc at all, and then I'm gonna let you know what happens.

**Comment by XP-Fan** [comment]
Well, yeah: Actually, now it's working fine. You're a real genius!

**Comment by XP-Fan** [comment]
Well, which codepage does whapp-irc prefer/use? As german signs like ä, ö and ü are arriving as mathematical characters.

**Comment by XP-Fan** [comment]
Well, looks like it works only once. As soon as I log off and log on, I can neither send nor receive, nor do I get even some confirmation that I am ready for messages, or a new QR-Code. Just nothing.

**Comment by lieuwex** [comment]
Happy to hear it kinda works!

About the encoding issues, is it happening on both send and receive or only one of the two?
whapp-irc doesn't really do anything special, which basically reduces to using UTF-8, IRC basically says that clients and servers can do whatever about character encodings (but it's canonical nowadays to use UTF-8).

I guess Miranda NG should've an option to select the encoding for a server, I'm not sure, really.

About the logging off and logging on error, whapp-irc currently has a bug (for which I should probably open an issue) where you sometimes have to reconnect multiple times before it will log on. Basically, sometimes it silently fails, if you don't receive anything from 'status' after 1 minute or so I would reconnect and try again.

**Comment by XP-Fan** [comment]
Well, I can not join group chat channels. Any ideas why?

**Comment by lieuwex** [comment]
Hmm weird, any error whatsoever?
You should be able to join a channel using the name converted to ascii without spaces: for example to join a chat named 'Umlaüt Test' you should be able to join '#UmlautTest'

**Comment by lieuwex** [comment]
Oh and whapp-irc doesn't really yet handle group chat name changes in the best way possible, since that's a bit problematic with IRC.

**Comment by XP-Fan** [comment]
The whatsapp-group is "test" and if I want to join it, I basically get an names-list within the server window, but that's everything. The chatroom does just not create. This is for both whether I try it over the channels list, where it is basically listed, or with that "enter the name-box", where I entered "#test"

**Comment by XP-Fan** [comment]
do you have an idea what I can do with this group chat problem? The guys in my university are expecting me to join the IT-Group.

**Comment by XP-Fan** [comment]
I just send you some stuff personally that coult be interesting.

**Comment by lieuwex** [comment]
Looking at the logs, weirdly, it looks fine again. I will again take a look if I forgot something (just like connecting), but I'm not sure, really. Miranda is a bit strict in following the IRC protocol and whapp-irc's IRC base was a bit hacked together.

**Comment by lieuwex** [comment]
It seems to be correct to be honest, it also doesn't work when somebody in the chat sends a message? Or if you send a message using your phone? This is really weird to be frank.

**Comment by XP-Fan** [comment]
Well, just another thing: Can I use multiple WhatsApp-Accounts with multiple IRC-Nicknames? As I just made a Typo and it prompted me to scan a code.

**Comment by XP-Fan** [comment]
No, actually they were inviting me into the group on real Whatsapp even while whapp-irc was running. I didn't even notice the group within whapp-irc but of course on my phone.

**Comment by XP-Fan** [comment]
If you don't mind, I would ask my mother to make some photos of the miranda IRC-settings-dialogs.

**Comment by XP-Fan** [comment]
Well, as my mother is cleaning the windows, maybe you like to have a look at them over skype?

**Comment by XP-Fan** [comment]
Well, anyway: Maybe you could also make an alternative replay capability which gets enabled by sending some certain message to the status?

**Comment by XP-Fan** [comment]
As far as the oining problem is concerned: I realized that Miranda recently made an update off their IRC-plugin (irc.dll). I'm gonna replace this with the old version and retry.

**Comment by XP-Fan** [comment]
Okay, well, no, I can not use the old version of the DLL, it refuses loading. I'm gonna downgrade the whole miranda, (of course a copy, not my original version.)

**Comment by XP-Fan** [comment]
Well, it doesn't help.

**Comment by lieuwex** [comment]
You can indeed setup multiple whatsapp profiles using different IRC nicknames. Although only one can be connected at the same time currently (a known problem I've been wanting to fix for a while).

The screenshots might be useful, I will try to re-install skype on my PC here so we have a better way to talk.

The alternative replay capability is a really good idea actually! I will implement it ASAP.

**Comment by lieuwex** [comment]
I implemented the alternative replay capability, you can enable it by running:

```
docker rm -f whapp-irc
docker pull lieuwex/whapp-irc
docker run -d \
	--name whapp-irc \
	-v "$HOME/.whatsapp:/root" \
	-p 6667:6060 \
	-p 3000:3000 \
	-e "HOST=server.neverseen.de" \
	-e "LOG_LEVEL=verbose" \
	-e "REPLAY_MODE=alternative" \
	--restart=always \
	lieuwex/whapp-irc
```

**Comment by lieuwex** [comment]
What it does is sending replayed messages to 'replay' containing every message. It _should_ work, didn't test it thoroughly though.

**Comment by XP-Fan** [comment]
Well, actually, if you don't like skype, we can also do WhatsApp-calls if you prefer these. However: I do often fail in accepting them, so basically if you call and I decline by mistake, just wait, I'm gonna call you back then.

**Comment by XP-Fan** [comment]
Well, looks like the alternate replay works for private chats, but unfortunately it is also missing the groupchats.

**Comment by XP-Fan** [comment]
I think I got it! As I was just comparing the server logs of freenode (an public IRC-service), and whapp-irc, I figured out that actually after joining the channel, whapp-irc sends the users list, but other than the freenode, it doesn't include the IRC-user that joined itself. This is just a guess, but it could be?

**Comment by XP-Fan** [comment]
Well, looks like I found a solution at least for my personal usecase: You remember this IRC-XMPP-Transport? There the groupchats do work, and I found a solution on how to tell it that it should disconnect from the IRC-Server now, which basically fixes the dynamic IP-issue. Furthermore, other than the miranda IRC-Plugin, the XMPP-method gives me a server side synchronized contact list and the possibility to connect with multiple computers at a time, and anyway, I found the miranda IRC-Plugin sometimes taking 0.1% of my CPU, so I guess mirandas IRC-Implementation is just poorly written (unlike everything else from miranda), so I'll probably prefer the XMPP-Transport in future. However: If you wanna make whapp-irc fully compatible with miranda anyway, I'll of course still help you. By the way: Thanks for this extremely awesome project, I suppose it's far beyond your imagination how much it helps me. Just an instance: Yesterday evening I was able to ask into my IT-Students group if someone can take me from hohenpolding to landshut, so a guy called alex who was on the same way fetched me, and I was able to join the semester opening party, where I made great new contacts…

**Comment by lieuwex** [comment]
Sorry again for the late reply, I keep forgetting to come back to you when I see a mail.

Glad to hear it's fixed! Everything works now If I understand you completely, right? That's great :)

I'm really really happy to hear how much whapp-irc helps you, so glad! 😄 
I indeed never expected it to make such an impact, just wrote this quickly because I wanted to use weechat for all my messaging (using keyboard shortcuts and plugins) instead of having to switch to a clunky browser.
I can't really express good what I'm trying to say, but I'm really glad it helps and hope it continues to help you, haha.

If you have any questions still I'm glad to answer, I will take a look still at miranda, but I'm still busy with a lot of stuff haha.

**Comment by lieuwex** [comment]
Closing this too, since it feels like it's working now, am I right? 😉
