### ISSUE TITLE
Optional Emoji Handling/Conversion

### ISSUE THREAD

**Issue by MarvAmBass** [lieuwex/whapp-irc#35]
I'd like to implement some module which translates emojis to thier ascii counter part like this:

🍫 -> `:chocolate_bar:`

 and vice versa

`:chocolate_bar:` -> 🍫

I could use a map like this https://github.com/kyokomi/emoji/blob/master/emoji_codemap.go to do the conversion.

Since some people might actually prefer the emojis (cause they have a great support in thier client) I'd keep this optional and add some ENV which would enable this module like:

`ENABLE_EMOJI_CONVERSION=true`

What do you think about this? Would you merge it if it's properly implemented?
Thanks

**Comment by lieuwex** [comment]
Sorry I completely forgot about this issue.

It's an interesting idea, but I feel like this is a bit out-of-scope for whapp-irc.
This feels like it has a better place as a plugin in a chat client, many clients have excellent scripting support.

Of course if you'd really like this I would encourage to maintain a fork, but I don't think I would merge it onto master.

**Comment by lieuwex** [comment]
Hahah indeed :P, well you could've always have your own fork otherwise haha.
Good luck!
