### ISSUE TITLE
pull requests and issues

### ISSUE THREAD

**Issue by skibz** [lieuwex/whapp-irc#42]
i realise that this is a personal tool, and that you can't be held liable for anything for obvious legal reasons, and that you don't appear to have made any guarantee of support for the tool, but i just wanted to determine whether you are receptive to outside influence for how the project moves forward/ideas/etc?

**Comment by lieuwex** [comment]
nah this is just fully personal, if you want to do stuff, fork it. Be sure to make the code somewhere public, since it's GPLv3.
